using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Skerga.Godot.DependencyInjection;

[Generator]
public class DiMethodGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName("Godot.DependencyInjection.InjectAttribute",
                predicate: (c, _) => c is ParameterSyntax,
                transform: (n, _) => n.TargetNode.Parent!.Parent as MethodDeclarationSyntax)
            .Where(m => m is not null);
        
        var compilation = context.CompilationProvider.Combine(provider.Collect());
        
        context.RegisterSourceOutput(compilation,
            (spc, source) => Execute(spc, source.Left, source.Right!.Distinct().ToImmutableArray()!));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<MethodDeclarationSyntax> methodList)
    {
        foreach (var methodSyntax in methodList)
        {
            if (compilation
                    .GetSemanticModel(methodSyntax.SyntaxTree)
                    .GetDeclaredSymbol(methodSyntax) is not IMethodSymbol symbol)
                continue;
            
            var builder = new StringBuilder();
            // iterate over all parameter that have no Inject Attribute.
            foreach (var param in from param in symbol.Parameters 
                     let ct = Enumerable.Any(param.OriginalDefinition.GetAttributes(), attr => 
                         attr.AttributeClass?.ToDisplayString() == "Godot.DependencyInjection.InjectAttribute") 
                     where !ct select param)
            {
                builder.Append(param.Type.ToDisplayString());
                builder.Append(" ");
                builder.Append(param.Name);
                builder.Append(", ");
            }
            builder.Length -= builder.Length > 0 ? 2 : 0;
            var methodParameters = builder.ToString();
            
            builder.Clear();
            foreach (var param in symbol.Parameters)
            {
                if(param.OriginalDefinition.GetAttributes()
                   .Any(attr => attr.AttributeClass?.ToDisplayString() == "Godot.DependencyInjection.InjectAttribute"))
                {
                    builder.Append($"global::Godot.DependencyInjection.DependencyInjection.GetService<{param.Type.ToDisplayString()}>(), ");
                    continue;
                }
                builder.Append($"{param.Name}, ");
            }
            builder.Length -= builder.Length > 0 ? 2 : 0;
            var callParameters = builder.ToString();

            var className = symbol.ContainingType.Name;
            var methodName = symbol.Name;
            var returnType = symbol.ReturnType.ToDisplayString();
            var namespaceName = symbol.ContainingType.ContainingNamespace.ToDisplayString();
            var access = symbol.DeclaredAccessibility.ToString().ToLower();
            var staticV = symbol.IsStatic ? "static " : "";
            var asyncV = symbol.IsAsync ? "async " : "";
            var isGlobal = namespaceName == "<global namespace>";
            var ret = returnType != "void" ? "return " : "";
            
            var source = $$"""
                           // <auto-generated/>
                           namespace {{namespaceName}}
                           {
                               public partial class {{className}}
                               {
                                   {{access}} {{staticV}}{{returnType}} {{methodName}}({{methodParameters}})
                                   {
                                        {{ret}}{{methodName}}({{callParameters}});
                                   }
                               }
                           }
                           """;
            
            var globalSource = $$"""
                                 // <auto-generated/>
                                 public partial class {{className}}
                                 {
                                     {{access}}{{staticV}}{{asyncV}}{{returnType}}{{methodName}}({{methodParameters}})
                                     {
                                          {{ret}}{{methodName}}({{callParameters}});
                                     }
                                 }
                                 """;
            
            context.AddSource($"{className}{methodName}{methodParameters}.g.cs", isGlobal ? globalSource : source);
        }
    }
}