using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Skerga.Godot.DependencyInjection;

[Generator]
public class InjectAttributeGenerator : IIncrementalGenerator
{
    private const string AttributeSourceCode = $$"""
                                                 // <auto-generated/>
                                                 namespace Godot.DependencyInjection
                                                 {
                                                     [global::System.AttributeUsage(global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Parameter)]
                                                     public class InjectAttribute : global::System.Attribute
                                                     {
                                                     }
                                                 }
                                                 """;
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "InjectAttribute.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));
    }
}